name: Example for support AT diskuv.com

on:
  push:
    branches:
      - 'main'

jobs:
  example:
    if: "true" # false disables this example
    runs-on: windows-latest
    name: Example
    steps:
      # STEP A
      # ------
      # Reproducing this on your own machine?
      # 1. Just click the link setup-diskuv-ocaml-windows_x86_64-0.4.0.exe below
      #    and run it! -OR-
      # 2. Open a PowerShell window and copy-paste all the "run:" lines
      - name: Download and install DKML (Windows-friendly Diskuv OCaml distribution)
        shell: powershell
        env:
          # Simple PATH to mimic minimal Windows setup, without Cygwin!
          PATH:
            "C:\\Windows\\system32;\
            C:\\Windows;\
            C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\"
        run: |
          Invoke-WebRequest -OutFile setup.exe https://github.com/diskuv/dkml-installer-ocaml/releases/download/v0.4.0-prerel42/setup-diskuv-ocaml-windows_x86_64-0.4.0.exe
          & .\setup.exe --ci -v -v

      # STEP B
      # ------
      # Reproducing this on your own machine?
      # YOU DON'T NEED THIS STEP!
      # This is just a GitHub patch since its PATH configuration is unusual.
      - name: Adjust PATH for GitHub Actions (already done by setup.exe on normal PC)
        shell: powershell
        run: |
          echo "$env:LOCALAPPDATA\Programs\DiskuvOCaml\0\usr\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          echo "$env:LOCALAPPDATA\Programs\DiskuvOCaml\0\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      # STEP C
      # ------
      # Reproducing this on your own machine?
      # 1. Open a **new** Command Prompt and copy-paste all the "run:" lines
      - name: Install an OCaml package using Opam
        shell: cmd
        run: |
          echo %PATH%

          REM Make an empty directory
          mkdir example
          cd example

          REM Create a local Opam switch, and use it
          opam dkml init
          for /f "tokens=*" %%i in ('opam env') do @%%i

          REM Install any OCaml package. We use 'diskuvbox' for an easy example
          opam install diskuvbox

          REM Run the OCaml compiled binary for diskuvbox
          diskuvbox tree -d 5 %LOCALAPPDATA%\Programs\DiskuvOCaml
